stages:
  - build
  - linting
  - test
  
build-job:
  image: node:14.21.1
  stage: build
  script:
    - cd ./localAppIntegration/client-2
    - npm install
    - echo "Build successful"


black:
  stage: linting 
  image: registry.gitlab.com/mafda/python-linting
  script: 
    - cd ./localAppIntegration/flask-2
    - black server.py
    - black courseSearch.py
    - echo "Fixing python lint issues."


eslint:
  image: node:14.21.1
  stage: linting
  script:
    - cd ./localAppIntegration/client-2/
    - npm install --save-dev eslint
    - npm init @eslint/config
    - npx eslint ./src/App.js
  

test:
  image: node:14.21.1
  type: test
  stage: test
  script:
    - cd ./localAppIntegration/flask-2
    - python -c 'import courseSearch; print (courseSearch.courseSearchFunction("CIS*3760", "coursesFall.json"))'
    # - cd ./localAppIntegration/client-2
    # - npm install
    # - npm install --save-dev jest babel-jest @babel/preset-env @babel/preset-react react-test-renderer
    # - npm i jest ts-jest babel-jest
    # - npm test
